In [1]:
import pandas as pd
import re
import nltk
nltk.download('stopwords')

import warnings
warnings.filterwarnings("ignore")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\91955\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [2]:
data = pd.read_csv("spamham.csv",usecols=['Message','Label'])
data.head()

  Label                                            Message
0   ham  Subject: enron methanol ; meter # : 988291\nth...
1   ham  Subject: hpl nom for january 9 , 2001\n( see a...
2   ham  Subject: neon retreat\nho ho ho , we ' re arou...
3  spam  Subject: photoshop , windows , office . cheap ...
4   ham  Subject: re : indian springs\nthis deal is to ...

In [3]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []

for i in range(0,len(data)):
    review = re.sub('[^a-zA-Z]',' ',data['Message'][i])
    review = review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [4]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()
x = cv.fit_transform(corpus).toarray()
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [5]:
y = data['Label'].map({'ham':0,'spam':1})
y

0        0
1        0
2        0
3        1
4        0
        ..
10157    1
10158    0
10159    0
10160    0
10161    0
Name: Label, Length: 10162, dtype: int64

## Grid Search

- `GridSearchCV` is a technique to search through the best parameter values from the given set of the grid of parameter,It is basically a cross-validation method. the model and the parameters are required to be fed in **Best Parameter** values are extracted and then the predcition are made

In [6]:
from sklearn.model_selection import GridSearchCV
from sklearn.naive_bayes import MultinomialNB , GaussianNB
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score , classification_report , confusion_matrix
from sklearn.model_selection import train_test_split

In [7]:
models = {
    "Multinomial Naive Bayes":MultinomialNB(),
    "Gaussian Naive Bayes":GaussianNB(),
    "SVC":SVC()
}

In [8]:

x = x.astype('int32')

## Model Performance

In [9]:
def evaluate_models(x,y,models):

    x_train,x_test,y_train,y_test = train_test_split(x,y,random_state = 42,test_size = 0.2)

    models_list = []
    scores = []

    for i in range(len(list(models))):
        model = list(models.values())[i]
        model.fit(x_train,y_train)  # Training thr model

        # Make predictions
        y_pred = model.predict(x_test)

        score = accuracy_score(y_test,y_pred)


        model_name = list(models.keys())[i]

        print(f"---- Score for ---- {model_name}-----")

        print(f"{score}")

        models_list.append(model_name)
        scores.append(score)
    print()   
    report = pd.DataFrame()
    report['Model_name'] = models_list
    report['Score'] = scores
    return report

In [10]:
 import gc
# # Jo variables kaam ke nahi hain unhe delete karo
# # del purana_variable 
 gc.collect() # Ye forcefully memory release karega

0

In [11]:
report  = evaluate_models(x,y,models)

---- Score for ---- Multinomial Naive Bayes-----
0.9394982784062961
---- Score for ---- Gaussian Naive Bayes-----
0.926709296606001
---- Score for ---- SVC-----
0.9276930644367929

In [12]:
report.sort_values('Score')

                Model_name     Score
1     Gaussian Naive Bayes  0.926709
2                      SVC  0.927693
0  Multinomial Naive Bayes  0.939498

#### From the report above we can see that the `multinommial navie bayes`  is performing best will continue the training our model by using multinommial navie bayes algorithm.

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=1)

In [14]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((8129, 40272), (2033, 40272), (8129,), (2033,))

In [15]:
from sklearn.naive_bayes import MultinomialNB
mnb_model= MultinomialNB()
mnb_model

MultinomialNB()

In [16]:
param_grid = {'alpha':[0.001]}
param_grid

{'alpha': [0.001]}

In [17]:
from sklearn.linear_model import Lasso 
lasso = Lasso()
lasso

Lasso()

In [18]:
from sklearn.model_selection import GridSearchCV
mnb_cv = GridSearchCV(estimator=mnb_model,param_grid = param_grid,cv =5)
mnb_cv

GridSearchCV(cv=5, estimator=MultinomialNB(), param_grid={'alpha': [0.001]})

In [19]:
mnb_cv.fit(x_train,y_train)

GridSearchCV(cv=5, estimator=MultinomialNB(), param_grid={'alpha': [0.001]})

In [20]:
print("tunned hyperparameter :(best parameter)",mnb_cv.best_params_)

print("Accurcy:",mnb_cv.best_score_)

tunned hyperparameter :(best parameter) {'alpha': 0.001}
Accurcy: 0.9207768379222253

In [21]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report

spam_detect_model = MultinomialNB(alpha = 3)
spam_detect_model.fit(x_train,y_train)
y_pred = spam_detect_model.predict(x_test)
confusion_m = confusion_matrix(y_test,y_pred)
accuracy = accuracy_score(y_test,y_pred)
classification_report = classification_report(y_test,y_pred)

In [22]:
print(f"Accuracy of the model is : {accuracy}")
print(f"Confusion matrix is :\n{confusion_m}")
print(f"Classification Report is :\n{classification_report}")

Accuracy of the model is : 0.9463846532218396
Confusion matrix is :
[[1536   57]
 [  52  388]]
Classification Report is :
              precision    recall  f1-score   support

           0       0.97      0.96      0.97      1593
           1       0.87      0.88      0.88       440

    accuracy                           0.95      2033
   macro avg       0.92      0.92      0.92      2033
weighted avg       0.95      0.95      0.95      2033

- So we can see that the model performed well and we have got acuracy of 94.63 models and we will selecting the model

In [28]:
import pickle
import os

if not os.path.exists('model'):
    os.makedirs('model')

with open('model/vectorizer.pkl', 'wb') as f:
    pickle.dump(cv, f)

with open('model/spam_detect_model.pkl', 'wb') as f:
    pickle.dump(spam_detect_model, f)

print("Sucessfully saved")

Sucessfully saved

In [31]:

import flask;
print(flask.__version__)

3.0.3